### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by pescepalla** [MaxVerevkin/i3bar-river#10]
1. The documentation contains the following snippets:
```
[theme]
name = "native"
```
```
[theme]
name = "slick"
```
However, this does not work and results in an error message

`"Failed to deserialize TOML file /home/me/.config/i3status-rust/config.toml at line 1: unknown field `name`, expected `theme` or `overrides`"`

Please replace `name` with `theme`.

2. Colors as expressed in the documentation result in i3bar-river failing to deserialize the config. They have to be expressed as `#00000000`

**Comment by MaxVerevkin** [comment]
Thanks, fixed!
