### ISSUE TITLE
`pkill -SIGUSR1 i3bar-river` does not make bar reappear

### ISSUE THREAD

**Issue by pescepalla** [MaxVerevkin/i3bar-river#12]
Contrary to manual suggestion ("Show/hide with pkill -SIGUSR1 i3bar-river"), `pkill -SIGUSR1 i3bar-river` hides the bar (reserving space) but does not show it.

To make the bar reappear, it is necessary to relaunch, but then the user is left with two `i3bar-river` processes.

A workaround I'm using so far is `pkill i3bar-river 2> /dev/null || i3bar-river`. 

WM: hyprland-nvidia
OS: Arch

**Comment by MaxVerevkin** [comment]
It works perfectly fine on river. It most probably is a hyprland bug: https://github.com/hyprwm/Hyprland/issues/2012

**Comment by vilhalmer** [comment]
Just a note that this appears to affect niri as well in case others find their way here. Going to see if I can prove this is the case, and open an issue.

**Comment by MaxVerevkin** [comment]
> Just a note that this appears to affect niri as well in case others find their way here. Going to see if I can prove this is the case, and open an issue.

Hyprland works now. Without further investigation I would guess that this is a niri problem.
