### ISSUE TITLE
[river] show current mode

### ISSUE THREAD

**Issue by mhmdanas** [MaxVerevkin/i3bar-river#14]
Similar to swaybar:
![image](https://github.com/MaxVerevkin/i3bar-river/assets/32234660/846b2211-d659-46e7-8d9d-3cdcd52fe816)

**Comment by MaxVerevkin** [comment]
I wonder what is the best way to configure it and how it may relate to layout name. I guess something like this might work:

```toml
layout_left = ["tags", "layout_name", "mode"]
```

**Comment by MaxVerevkin** [comment]
You can try #15
