### ISSUE TITLE
Allow passing config file path to command

### ISSUE THREAD

**Issue by mhmdanas** [MaxVerevkin/i3bar-river#16]
With swaybar, I have both a top and a bottom bar on the same screen, which I achieve by having multiple bar configs. This doesn't seem to be possible with i3bar-river, so I think it would be nice to allow passing a path to the config file to use, like so: `i3bar-river -c ~/.config/i3bar-river/config-bottom.toml`.

**Comment by mhmdanas** [comment]
Bonus: allow "including" another .toml file (whether from the config file itself or from the command line), so that the common configuration can be shared between bars.

**Comment by MaxVerevkin** [comment]
Implemented in d1fe8e5.

> allow "including" another .toml file (whether from the config file itself or from the command line)

TBH this seems a bit overkill, at least for now.

**Comment by mhmdanas** [comment]
Wow, I didn't expect this to get implemented that fast. Cheers!

> TBH this seems a bit overkill, at least for now.

Maybe, I just thought I should throw it out anyway since it came to mind. It's a bit inconvenient to have to duplicate options between config files, but I can live with it.

**Comment by MaxVerevkin** [comment]
You may have a script which assembles your two configs from three parts, but I don't know how (in)convenient that would be.
