### ISSUE TITLE
Tag background colors stack up

### ISSUE THREAD

**Issue by mhmdanas** [MaxVerevkin/i3bar-river#17]
This is how my i3bar-river config looks with a transparent `tag_bg` and `tag_focused_bg`:
![image](https://github.com/MaxVerevkin/i3bar-river/assets/32234660/6478240a-8873-4122-b10c-1373ae377e95)

So the background colors of the tags stack up on the background color of the bar as a whole, which is contrary to swaybar's behavior but also something I find generally confusing and unintuitive. Instead, I think the background color of the tags should only be determined by `tag_bg` (or the appropriate config variable).

**Comment by MaxVerevkin** [comment]
Yes, tags (and any other graphics drawn) blend with the background. Can you share a screenshot of the expected behavior? To me, transparent `tag_bg` mean that tags should not have a background, which is the case in your screenshot.

**Comment by mhmdanas** [comment]
> To me, transparent tag_bg mean that tags should not have a background, which is the case in your screenshot.

Sorry, I guess my screenshot isn't clear because of the transparency, but their background is in fact the same as the rest of the bar. Here's an image that makes that clearer:

![image](https://github.com/MaxVerevkin/i3bar-river/assets/32234660/3fb1fcb6-92ce-419f-994d-04f22dd3d75e)


`tag_bg` and `tag_focused_bg` are also transparent here, so the tag takes on the color of the bar, but what I would expect is for it to take on the color of the background image instead.

> Can you share a screenshot of the expected behavior?

Here's swaybar with the workspace colors set to transparent:

![image](https://github.com/MaxVerevkin/i3bar-river/assets/32234660/69b39cd2-2983-4936-bbf2-bd523147761c)

Does that make what I mean clearer?

**Comment by MaxVerevkin** [comment]
> Does that make what I mean clearer?

Yes. Does swaybar render (blend) everything like this, including status line, or just the workspaces?

**Comment by mhmdanas** [comment]
swaybar uses the normal bar background for the rest of the bar (including the status line). The only other thing in the bar with a separately configurable background is `binding_mode`, which is also rendered like this.

**Comment by mhmdanas** [comment]
> Just to clarify, I mean if you set blocks background to transparent directly in JSON, do you see your bar's background or your wallpaper (like you do with workspaces)?

Right, I forgot that I can set the block's background in the JSON output. Anyway, again, I see my wallpaper:

![image](https://github.com/MaxVerevkin/i3bar-river/assets/32234660/93913998-ec2b-4607-9f6c-30c046f78450)

> Interesting, for me its the opposite :) I guess I can add blend option to configure this. blend = true would be the current behavior and blend = false is what swaybar does.

Sure, that's an acceptable solution for me. We can bikeshed on the default value later. :P

**Comment by MaxVerevkin** [comment]
Here you go e07d987

**Comment by mhmdanas** [comment]
Thanks again!
