### ISSUE TITLE
Clip status line instead of overflowing

### ISSUE THREAD

**Issue by mhmdanas** [MaxVerevkin/i3bar-river#18]
i3bar-river:

![image](https://github.com/MaxVerevkin/i3bar-river/assets/32234660/b4de6822-fd19-47b8-94ad-96cfc554936a)

Compare swaybar:

![image](https://github.com/MaxVerevkin/i3bar-river/assets/32234660/41e15bb1-18ac-448d-90c4-68ab877aa47b)

swaybar also has a config option `status_edge_padding` that sets the padding between the status line and the bar, which could also be added:

       status_edge_padding <padding>
           Sets the padding that is used when the status line is at the right
           edge of the bar. This value will be multiplied by the output scale.
           The default is 3.

**Comment by MaxVerevkin** [comment]
Overflow fixed in f27d993.

Please open a separate issue for the feature request.

**Comment by MaxVerevkin** [comment]
> Or do you want an issue opened anyway?

No, I don't see a reason to have config options that nobody use :)
