### ISSUE TITLE
tag are too large

### ISSUE THREAD

**Issue by bda65hp** [MaxVerevkin/i3bar-river#2]
Hi,
is it possible to reduce the tag width?
I like the tag style of dwm, awesome an maybe i3.

**Comment by MaxVerevkin** [comment]
Right now the size is hard-coded. I'll add a configuration option for this soon.

**Comment by bda65hp** [comment]
Thanks.
This bar is great :)

**Comment by MaxVerevkin** [comment]
11f76444666d2e3d053c5d6bd4c7567fe86a2cd4
