### ISSUE TITLE
toggle bar as overlay

### ISSUE THREAD

**Issue by timhae** [MaxVerevkin/i3bar-river#30]
Hey, thanks for the great tool! I was wondering if it would be possible to add extra `position` options called `overlay_{top, bottom}` that render the bar without moving other windows out of the way. I vaule my screen real estate and would like to toggle the bar just when I am interested in the information :)

**Comment by MaxVerevkin** [comment]
You can already toggle the bar with `pkill -SIGUSR1 i3bar-river`. I assume what you want is a `layer` option with possible values `overlay`, `top`, `bottom` and `background`?

**Comment by timhae** [comment]
yes, exactly. I did find the toggle command in the readme. Also can I disable the workspace block? It seems to be enabled by default (not sure if this is because I am on hyprland).

**Comment by MaxVerevkin** [comment]
> Also can I disable the workspace block? It seems to be enabled by default

No, not yet.

**Comment by MaxVerevkin** [comment]
Implemented `layer` in a1a9933.

> without moving other windows

You can achieve this using something like:

```toml
height = 20
margin_bottom = -20
```

Not ideal, but it works :laughing:

**Comment by MaxVerevkin** [comment]
To hide tags/workspaces: d44a07d
