### ISSUE TITLE
Allow scrolling between workspaces

### ISSUE THREAD

**Issue by vpzomtrrfrt** [MaxVerevkin/i3bar-river#35]
Another feature I'm missing from sway, it would be nice to be able to switch between workspaces with the scroll wheel

**Comment by MaxVerevkin** [comment]
Yeah, seems reasonable. Just a few details:
1. Which direction corresponds to 'go left' and which to 'go right'?
2. River has tags instead of workspaces, and several tags can be active at the same time. What to do in thees cases?

**Comment by vpzomtrrfrt** [comment]
1. looks like scroll down for right, up for left
2. I can't really speak to what River users expect, as I've never used it. Maybe disable in that case or use only the leftmost tag?

**Comment by tunalad** [comment]
>     2. River has tags instead of workspaces, and several tags can be active at the same time. What to do in these cases?

you could shift them all together too. On dwm I use [this patch](https://dwm.suckless.org/patches/tagshift/), which deals with that problem (by just shifting everything)

**Comment by MaxVerevkin** [comment]
> looks like scroll down for right, up for left

Alright.

> you could shift them all together too

That's the easiest option a guess, and a sensible one too. Not sure about the wrapping around tag 9, river has 32 tags after all. I will probably not implement wrapping at all.

**Comment by tunalad** [comment]
> Not sure about the wrapping around tag 9, river has 32 tags after all.

maybe limit it to the `max_tags`, or a different config option to limit the number to. But I think this would just be useful for the visible tags on the bar, and not the ones you don't see

**Comment by MaxVerevkin** [comment]
Implemented in dbcaa19. On river it shift the tags until only one is focused (either the 1st or 32nd).
