### ISSUE TITLE
Errors in wm_info_provider are not reported

### ISSUE THREAD

**Issue by vpzomtrrfrt** [MaxVerevkin/i3bar-river#37]
Workspace display is no longer working for me after updating to 1.0.1. I see there is some code for handling errors, but it doesn't appear to be triggered properly, instead leaving the tag UI unresponsive

Adding in some extra logging reveals that `hyprland_cb` is returning an error:
```
Custom { kind: InvalidData, error: "Unknown workspace" }
```

(ideally it would just work but this might be caused by an issue in a plugin I'm using)

**Comment by MaxVerevkin** [comment]
Should be fixed in 7ff4f07.
