### ISSUE TITLE
Race condition(?) in hyprland event handling

### ISSUE THREAD

**Issue by vpzomtrrfrt** [MaxVerevkin/i3bar-river#38]
As I referenced in #37, the change in 778e88432d06c492a6611c8ed1464a423f67551a introduced a check that the selected workspace exists. This is done by requesting a list of workspaces, which breaks if the workspace was destroyed between its selection and the listing.

Specifically, I've observed this behaviour when using the [split-monitor-workspaces](https://github.com/Duckonaut/split-monitor-workspaces) plugin, as it creates and destroys several workspaces while initializing if `enable_persistent_workspaces` is 0

**Comment by MaxVerevkin** [comment]
May be fixed in cc5110a.

**Comment by vpzomtrrfrt** [comment]
Confirmed working for me now
