### ISSUE TITLE
Add support for Hyprland

### ISSUE THREAD

**Issue by user451421541757324** [MaxVerevkin/i3bar-river#4]
Hi, I'm trying i3bar-river on Hyprland (with i3status-rust) and it works almost perfectly.

The only thing that doesn't work is the workspace numbers, which don't appear at all. Could you support Hyprland too?

**Comment by MaxVerevkin** [comment]
AFAIK, Hyprland advertises it's workspace info via `ext-workspace-unstable-v1`, a protocol extension which uses `wayland-protocols` naming scheme but is not yet part of `wayland-protocols` (there is an [`open PR`](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40) to upstream it, under a different name), which is a bit sketchy.

I'm not against supporting it, but it will probably be behind a feature flag. Would you like to try implementing it? If not I'll look into it a bit later.

**Comment by user451421541757324** [comment]
> Would you like to try implementing it?

I'm really sorry, but I don't know Rust and not even Wayland protocols. I'm just a "normal user".

**Comment by MaxVerevkin** [comment]
@user451421541757324 I'm not very familiar with hyprland, so... Do you use multiple monitors? If so, do you expert to se the exact same set of workspaces on each display's bar? I think it would make sense for each bar to display only it's subset of workspaces, but it looks like hyprland does not share this information (even though protocol provides a way to do so).

**Comment by MaxVerevkin** [comment]
Ah, okay, I understand.

> but it looks like hyprland does not share this information

It does, but I couldn't make it to work because of a bug in hypland: https://github.com/hyprwm/Hyprland/issues/1466. Working around this bug is a bit awkward, so I'll wait for it to be fixed first.

**Comment by MaxVerevkin** [comment]
> I'm trying i3bar-river on Hyprland (with i3status-rust)

@user451421541757324 are you affected by https://github.com/hyprwm/Hyprland/issues/1485?

**Comment by user451421541757324** [comment]
> @user451421541757324 are you affected by [hyprwm/Hyprland#1485](https://github.com/hyprwm/Hyprland/issues/1485)?

I'm not:

- hyprland v0.21.0beta
- i3bar-river compiled before [92a7a55](https://github.com/MaxVerevkin/i3bar-river/commit/92a7a55e18752147f71fa4155ee74b948d78a3de)
- i3status-rust 0.22.0-1

I'll compile i3bar-river with recent commits too, and I will let you know.

**Comment by MaxVerevkin** [comment]
> i3status-rust 0.22.0-1

I'm using latest master, might be relevant... BTW it happens only when I click on a block, like 5 times.

**Comment by user451421541757324** [comment]
> it happens only when I click on a block, like 5 times.

I compiled last i3bar-river and I clicked more than five times on various blocks, but I still cannot reproduce:

- Music block
- Weather block
- Time block

**Comment by MaxVerevkin** [comment]
@user451421541757324 WIP: https://github.com/MaxVerevkin/i3bar-river/tree/hyprland

**Comment by user451421541757324** [comment]
Hi, thanks for the update! Am I able to test it?

I compiled it, but I cannot see any block (no workspaces block and no normal blocks (music, date...)).

**Comment by MaxVerevkin** [comment]
Make sure to use the latest hyprland version (from the master branch). It... works for me?

**Comment by user451421541757324** [comment]
You are right, with the latest hyprland everything works fine.

**Comment by MaxVerevkin** [comment]
> everything works fine.

Except "click to focus" :)

**Comment by MaxVerevkin** [comment]
> > everything works fine.
> 
> Except "click to focus" :)

Which is blocked by https://github.com/hyprwm/Hyprland/issues/2084
