### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by GuyLiner** [MaxVerevkin/i3bar-river#5]
Is it cool if I try to submit an AUR package for this?

**Comment by MaxVerevkin** [comment]
Sure!

**Comment by GuyLiner** [comment]
https://aur.archlinux.org/packages/i3bar-river-git
Let me know if you'd prefer any of the build steps to be different. I just copied the i3bar-river binary to /usr/bin/.

**Comment by MaxVerevkin** [comment]
Thanks for packaging it! Here are a few nitpicks:

* River is not a dependency for this project (it can run in any wlroots-based wm, but workspaces/tags only work in river at the moment). And even if it was, I think many people still build river from source.
* I would prefer `cargo install` to include `--locked` option (just added it in the readme). See https://github.com/rust-lang/cargo/issues/7169.

**Comment by GuyLiner** [comment]
Alrighty, should be updated now. Thank you as well for the program, it's great.
