### ISSUE TITLE
Default XDG_CONFIG_HOME has broken

### ISSUE THREAD

**Issue by duckbilledwren** [MaxVerevkin/i3bar-river#6]
It looks like in the process of removing the dirs_next dependency, the function that finds the default XDG_CONFIG_HOME path (`config_dir()` in config.rs) accidentally changed to looking for `$HOME/config` instead of `$HOME/.config` (the initial period in the config directory has been removed).

**Comment by MaxVerevkin** [comment]
Thanks for pointing out, fixed.
